version: '3:8'

networks:
  app-network:
    driver: bridge

services:
  backend: 
    image: balaji236/troveapp-backend:test
    build:
      context: /Trovebackend
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
    networks:
      - app-network
    restart: always

  frontend:
      image: balaji236/troveapp-frontend:test 
      build:
        context: /Trovefrontend
        dockerfile: Dockerfile
      ports:
        - 8080:80
      environment:
        NODE_ENV: production
        REACT_APP_BACKEND_URL: http://localhost:5000/
      depends_on:
        - backend
      networks:
        - app-network
      restart: always
      